name: graph_plus
version: 1.0.0-alpha
description: >-
  Provides graphing and drawing features with a focus on software architecture diagramming capabilities
repository: https://github.com/ArchMindCo/flutter-graph-plus
topics:
  - graphing
  - diagramming
  - utils
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  core_extras: ^1.0.3-alpha
  graph_plus_exporter: ^1.0.0-alpha
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
